version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build completed successfully!
artifacts:
  files:
    - index.html
    - app.css
    - image.png
